### ISSUE TITLE
Why are uv.fs_event_start and uv.fs_poll_start not included in coop ?

### ISSUE THREAD

**Issue by Lcchy** [gregorias/coop.nvim#2]
Hi, first of all, I would like to thank you for this very clear and nicely structured project. I am starting to write my own nvim extensions and coop (and your blog posts) really helped with the confusions I had regarding plenary async, thanks!

I am writing a small utility in which I want to spawn a coroutine that waits for a specific file to exist, then do something, like notify the user.
My first approach was to write a while loop like this:

```
local file_path = "/foo/bar"

coop.spawn(function()
	while true do
		local _, stat = coop_uv.fs_stat(file_path)

		if stat then
			-- notify user
			vim.notify("File exists")
			break
		end

		-- sleep , check if task got cancelled
		local success, err_msg = copcall(coop_uv.sleep, 100)
		if not success and err_msg == "cancelled" then
			vim.notify("File watcher cancelled!")
			break
		end
	end
end)
```

But this is quite long, and I saw that `uv.new_event_start()` exists, which looks like its the perfect solution to watch the fs.

I saw that coop doesnt wrap this, but didn't understand the reason given here: https://github.com/gregorias/coop.nvim/blob/426dfe8b336b4b271c0e6efed325de1fca9745d1/lua/coop/uv.lua#L170C1-L173C1

Is there a coop way of watching for specific filesystem changes ?
Thanks a lot in advance.

**Comment by gregorias** [comment]
Hi @Lcchy,

Thank you for your kind words, and I’m glad that you are finding this project useful.

The reason why I didn’t import [`uv.fs_event_start`](https://neovim.io/doc/user/luvref.html#uv.fs_event_start()) and the other function is that the callback there is not a continuation. `uv.fs_event_start` doesn’t call its callback once it’s done (like a continuation) but instead [it calls the callback repeatedly with new events](https://neovim.io/doc/user/luvref.html#uv.fs_event_start():~:text=Start%20the%20handle%20with%20the%20given%20callback%2C%20which%20will%20watch%20the%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20specified%20path%20for%20changes.).

As for your intent, you can relatively easily turn it into an awaitable with queues like so:

```lua
local MpscQueue = require('coop.mpsc_queue').MpscQueue
local q = MpscQueue.new()

uv.fs_event_start(…,
  function(...)
    q:push({ ... })
  end
)

coop.spawn(function()
  while true do
    local results = q:pop()
    your_logic(results)
  end
end)
```

I believe this pattern is more straightforward than trying to wrap `uv.fs_event_start` into a coroutine.

Feel free to reopen this issue if I missed something.

**Comment by Lcchy** [comment]
Oh I see, thanks a lot for the explanation! A queue does seem appropriate in this case.
