### ISSUE TITLE
Add a wrapper function to immitate vim.system() ?

### ISSUE THREAD

**Issue by Lcchy** [gregorias/coop.nvim#3]
While using coop.nvim I wanted to execute a quick shell command in a task function and use its results directly afterwards, ie do it synchronously.

I first tried to use `require("coop.uv").spawn` which wraps `uv.spawn`, but it is as fidly and complex because of the necessary await() on the future and the stdout piping.

I believe this is why `vim.system()` was introduced as an easy-use wrapper around `uv.spawn`.

Would it be possible to add a similar wrapper, but that uses coop.uv underneath?

Or is there no drawback to using `vim.system()` in a task function direclty? This is what I've settled with at the moment.

My understanding is sadly too limited to submit a PR myself and I perfectly understand if this is out of scope for the project. Its more of a question I had.

**Comment by gregorias** [comment]
There’s [a subprocess interface](https://github.com/gregorias/coop.nvim?tab=readme-ov-file#coopsubprocess) that provides a flexible way for launching subprocesses modeled after Python’s `subprocess` module. You can check the example for how to launch something and read its output. Does that work for you?

**Comment by gregorias** [comment]
`vim.system` could be added, but I’d prefer not to do add yet another way to do subprocesses at this moment unless `vim.system` provides some unique advantages.

Feel free to reopen if this answer do not resolve the matter for you.

**Comment by Lcchy** [comment]
Alright yes I understand! Its just a convenience wrapper I think and so I agree that it doesn't need to be part of the project.
I will probably just write my own helper function.

**Comment by gregorias** [comment]
You know what, fair enough. Let’s add it for completeness’ sake.

**Comment by Lcchy** [comment]
Thanks a lot! That is very nice and worked well in my case.

**Comment by gregorias** [comment]
You’re welcome and thanks for letting me know it works.
