### ISSUE TITLE
Fix type annotations

### ISSUE THREAD

**Issue by gregorias** [gregorias/coop.nvim#4]
From [Reddit](https://www.reddit.com/r/neovim/comments/1hewakp/comment/m2vmfkc/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button):

> The only minor thing I noticed is that the type annotations are partly missing for some of the included modules, which was especially apparent for the vim.system wrapper.

It could be that type annotations don’t work if I use decorators to define a function.

**Comment by disrupted** [comment]
guy from Reddit here. thanks for looking into it. I can confirm the type annotations are working now
